name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install gmock & gtest
      run: sudo apt-get install libgmock-dev && cd /usr/src/googletest/googlemock/ && sudo mkdir build && sudo cmake .. && sudo make && sudo cp lib/*.a /usr/lib

    - uses: actions/checkout@v2

    - name: make ut
      run: cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++" . && make

    - name: ut
      run: ./ut.exe

    - name: ut coverage
      run: gcovr --config=ut/gcovr/gcovr.cfg
