name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: g++ -std=c++14 -fconcepts -I./src/queue -I../afum_trunk/UT/ src/queue/MtQueue.cpp ut/queue/MtQueueTest.cpp -lgtest -lgtest_main -lpthread
    - name: ut
      run: ./a.out
    - name: make distcheck
      run: make distcheck
